### ISSUE TITLE
Tietokannan suunnittelu

### ISSUE THREAD

**Issue by MacStache** [TVTKMO23-WP-GROUP-12/G12MovieDB#5]

**Comment by MacStache** [comment]
> Henri Laukka commented in Jira:

@Sanna M@Pasi Honka@Lari Lepistötsekkaatteko liitteenä olevan luonnoksen ja kommentoitte muutoksia?

**Comment by MacStache** [comment]
> Henri Laukka commented in Jira:

Päivitetty suunnitelma, tsekkaatteko ja kommentoitteko
[file id="ebf9fceb-9932-44d7-ab27-c691b86eb116"]
@Sanna M@Lari Lepistö@Pasi Honka

**Comment by MacStache** [comment]
> Pasi Honka commented in Jira:

Mun mielestä erittäin selkeä. User-taulun emailissa typo: varvhar

**Comment by MacStache** [comment]
> Sanna M commented in Jira:

Paljon parempi. username vois olla ‘unique’ samoin ‘email’ niin se tarkistaa ettei kahta samanlaista isketä kantaan, mietin myös sitä miten ryhmiin liitytään tai millä perusteella ihmiset ryhmäytyy, tässä taulussa siihen ei oteta kantaa ja tuleeko taulujen tietojen päivityksille aikaleima “updated_at”

**Comment by MacStache** [comment]
> Sanna M commented in Jira:

Mietin myös sitä että miten ne kutsut lähtee noihin ryhmiin, se pitää jotenkin käsitellä db:ssa tai ainakin tehdä näkyväksi, pitäiskö tohon group-tauluun laittaa jonkinlainen request_list tai request_status ja sit ehkä joined_at (left_at?) ja käyttäjällä on nyt kaks roolia user_id ja owner_id mietin miten se käytännössä toteutuu, pitäskö ennemminkin mennä sen kautta että is_owner ja tehdä sen ENUMilla

**Comment by MacStache** [comment]
> Sanna M commented in Jira:

tai periaatteessa is_admin (true/false)

**Comment by MacStache** [comment]
> Henri Laukka commented in Jira:

[file id="35b5735a-5cb0-4173-9d56-e9f8de577465"]
Muokattu taulua. Tein groupista hyppytaulun ja jaoin sen erikseen group_members ja group_invite -tauluihin. Membereissä on nyt is_admin ENUM. Invitessä on erikseen kenttä following ENUM, joka siis on 0 tai 1 sen perusteella, että seuraako kaksi ihmistä toisiaan, koska vain siten voi kutsua groupiin. Sama kenttä on myös follows -taulussa referoituna foreign keyllä. username ja email on nyt uniqueidentifier.



@Pasi Honka@Sanna M@Lari Lepistökommentteja?

**Comment by MacStache** [comment]
> Henri Laukka commented in Jira:

@Sanna M@Pasi Honka@Lari Lepistötsekkaatteko liitteenä olevan luonnoksen ja kommentoitte muutoksia?

**Comment by MacStache** [comment]
> Henri Laukka commented in Jira:

Päivitetty suunnitelma, tsekkaatteko ja kommentoitteko
[file id="ebf9fceb-9932-44d7-ab27-c691b86eb116"]
@Sanna M@Lari Lepistö@Pasi Honka

**Comment by MacStache** [comment]
> Pasi Honka commented in Jira:

Mun mielestä erittäin selkeä. User-taulun emailissa typo: varvhar

**Comment by MacStache** [comment]
> Sanna M commented in Jira:

Paljon parempi. username vois olla ‘unique’ samoin ‘email’ niin se tarkistaa ettei kahta samanlaista isketä kantaan, mietin myös sitä miten ryhmiin liitytään tai millä perusteella ihmiset ryhmäytyy, tässä taulussa siihen ei oteta kantaa ja tuleeko taulujen tietojen päivityksille aikaleima “updated_at”

**Comment by MacStache** [comment]
> Sanna M commented in Jira:

tai periaatteessa is_admin (true/false)

**Comment by MacStache** [comment]
> Henri Laukka commented in Jira:

[file id="35b5735a-5cb0-4173-9d56-e9f8de577465"]
Muokattu taulua. Tein groupista hyppytaulun ja jaoin sen erikseen group_members ja group_invite -tauluihin. Membereissä on nyt is_admin ENUM. Invitessä on erikseen kenttä following ENUM, joka siis on 0 tai 1 sen perusteella, että seuraako kaksi ihmistä toisiaan, koska vain siten voi kutsua groupiin. Sama kenttä on myös follows -taulussa referoituna foreign keyllä. username ja email on nyt uniqueidentifier.



@Pasi Honka@Sanna M@Lari Lepistökommentteja?

**Comment by sanna** [comment]
Please don’t tag me, I am not the Sanna involved in this ticket!- Sanna19 mars 2024 kl. 10:31 skrev Henri Laukka ***@***.***>:﻿

Henri Laukka commented in Jira:

@sanna ***@***.*** ***@***.*** Lepistötsekkaatteko liitteenä olevan luonnoksen ja kommentoitte muutoksia?

**Comment by MacStache** [comment]
I am sorry. Our Jira sync was doing weird stuff but I have since stopped it from syncing these comments.

Sorry for the inconvenience.

Yours truly,
Henkka Laukka

-------- Original Message --------
